name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          EC2_HOST="${{ secrets.EC2_HOST }}"
          ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts

      - name: Prepare script directory
        run: |
          ssh -i ~/.ssh/id_ed25519 \
            -p ${{ secrets.EC2_PORT }} \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            "mkdir -p ~/projects/twse/scripts"

      - name: Copy deploy.sh
        run: |
          scp -i ~/.ssh/id_ed25519 \
            -P ${{ secrets.EC2_PORT }} \
            scripts/deploy.sh \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/projects/twse/scripts/

      - name: Copy health_check.sh
        run: |
          scp -i ~/.ssh/id_ed25519 \
            -P ${{ secrets.EC2_PORT }} \
            scripts/health_check.sh \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/projects/twse/scripts/

      - name: Deploy
        run: |
          ssh -i ~/.ssh/id_ed25519 \
            -p ${{ secrets.EC2_PORT }} \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            "cd ~/projects/twse && chmod +x scripts/*.sh && bash scripts/deploy.sh"